# -*- coding: utf-8 -*-
"""task00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBsFn_PoTT5ngykUNmomleXCfCYQPlkT
"""

for i in range (1,100):
  if i % 3 == 0:
    print ("Fizz",end="")
    if i % 5 == 0:
      print("Buzz")
  elif i % 5 == 0:
    print("Buzz")
  else:
    print("\n",i)