# -*- coding: utf-8 -*-
"""task03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuLESGNspcZp2It0WyfsV302QFRWKCgI
"""

book1=open("Book1.txt").read().split()
words=open("20k.txt").read().split()
my_list =[]
def unique_words():
  for i in words:
    for j in book1:
      if i==j:
        if i in my_list:
          continue
        else:
          my_list.append(i)
        
  return(my_list)
#word = input("what word do you want to search?")
unique_words()

def count_the_article():
  
  wor_li=["a", "the", "at", "run", "to","and","are","or","for","an","this"]
  for i in wor_li:
    count =0
    for j in book1:
      if i==j:
        count =count +1
    print(i,"is present: ", count)
  
count_the_article()

def sorted_word():
  my_list=[]



t1=open("book1.txt").read().split()
def starts_with_vow():
  count =0
  vow=['a','e','i','o','u']
  for i in t1:
    letter = i[0]
    if letter in vow:
        count= count+1
        continue
    else:
        continue
  return(count)

starts_with_vow()

w1=open("wordtest.txt").read().split()
t1=open("test1.txt").read().split()

def rare_words():
  my_list = []
  for i in w1:
    for j in t1:
      if i!=j:
        if i in my_list:
          continue
        else:
          my_list.append(j)
        
  return(my_list)
rare_words()