# -*- coding: utf-8 -*-
"""task02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/178a7DhW06fcdU0UB3vckeLCxCLe96tF1
"""

file1= open("targettask2.txt",'r')
file3= open("file3.txt",'r+')
letter=file1.read()

for i in letter:
  
  if i =='o' or i=='O':
    a = '0'
  elif i=='a' or i=='A':
    a = '4'
  elif i =='e' or i=='E':
    a = '1'
  else:
    a = i

  file3.write(a)

file3.close()